name: '💼 Project Management Task'
description: For administrative, client communication, and other non-development tasks.
title: "[PM] - "
labels: 'project-management'
body:
  - type: textarea
    id: task-description
    attributes:
      label: "What is the administrative task?"
      description: "A clear description of the management task (e.g., \"Send weekly progress report to client,\" \"Schedule project milestone review call,\" \"Prepare and send monthly invoice\")."
    validations:
      required: true
  - type: dropdown
    id: cadence
    attributes:
      label: "Cadence"
      description: "Is this a one-time or recurring task?"
      options:
        - "One-Time"
        - "Weekly"
        - "Bi-weekly"
        - "Monthly"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Key Details & Checklist"
      description: "Provide the necessary details or a checklist for completing the task."
      placeholder: |
        - [ ] Action item 1
        - [ ] Action item 2
  - type: textarea
    id: people
    attributes:
      label: "People to Involve"
      description: "Who needs to be contacted or included? (e.g., Client's primary contact, accounting department)."
