name: "User Story"
description: "A small, self-contained feature from the user's perspective."
title: "[STORY] - "
labels: ["enhancement"]
assignees: "RenatoL"
body:
  - type: input
    id: user-story
    attributes:
      label: "User Story"
      description: "Describe the story using the format: 'As a [type of user], I want [to perform some action] so that [I can achieve some goal].'"
      placeholder: "As a user, I want to log in with my email so that I can access my account."
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Provide a checklist of specific, testable criteria that must be met for this story to be complete."
      placeholder: |
        - [ ] Given [context], when [I take an action], then [I see a result].
        - [ ] ...
    validations:
      required: true
  - type: input
    id: epic-link
    attributes:
      label: "Parent Epic"
      description: "If this story is part of an Epic, link to it here (e.g., #123)."
